const RECEIVE_AUTHENTICATION = 'RECEIVE_AUTHENTICATION';
const REQUEST_AUTHENTICATION = 'REQUEST_AUTHENTICATION';
const LOG_OUT = 'LOG_OUT';

export default {
    RECEIVE_AUTHENTICATION,
    REQUEST_AUTHENTICATION,
    LOG_OUT,
};