const RECEIVE_AUTHENTICATION = 'RECEIVE_AUTHENTICATION';
const REQUEST_AUTHENTICATION = 'REQUEST_AUTHENTICATION';
const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
const REQUEST_CURRENT_USER = 'REQUEST_CURRENT_USER';
const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER';
const LOG_OUT = 'LOG_OUT';

export default {
    RECEIVE_AUTHENTICATION,
    REQUEST_AUTHENTICATION,
    AUTHENTICATION_ERROR,
    REQUEST_CURRENT_USER,
    RECEIVE_CURRENT_USER,
    LOG_OUT,
};